# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20171001_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='client.Address'),
        ),
    ]
